In [26]:
import numpy as np
import math

In [27]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [28]:
a.ndim

1

In [29]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
b.shape

(2, 3)

In [31]:
a.dtype

dtype('int32')

In [32]:
c = np.array([2.2,5,1.1])
c.dtype.name 

'float64'

In [33]:
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
np.random.rand(2,3)

array([[0.42959847, 0.41678916, 0.1585681 ],
       [0.40055896, 0.21350634, 0.40435136]])

In [35]:
f = np.arange(10,50,2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [36]:
np.linspace(0,2,15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [38]:
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])


c = a-b
print(c)

d = a*b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [39]:
farenheit = np.array([0,-10,-5,15,0])

cel = (farenheit - 31) * (5/9)
cel

array([-17.22222222, -22.77777778, -20.        ,  -8.88888889,
       -17.22222222])

In [40]:
cel > -20

array([ True, False, False,  True,  True])

In [41]:
cel%2 == 0

array([False, False,  True, False, False])

In [42]:
A = np.array([[1,1],[0,1]])
B = np.array([[2,0],[3,4]])

a * b

array([ 10,  40,  90, 160])

In [43]:
A@B

array([[5, 4],
       [3, 4]])